### ISSUE TITLE
How Can I install plugins Local

### ISSUE THREAD

**Issue by Chasers9527** [adelf/idea-php-dotenv-plugin#38]
I can not install plugins local and  I can't serarch `.env files support`

I use phpstorm

![image](https://user-images.githubusercontent.com/16145443/61940860-de55dd80-afc8-11e9-8553-178441299983.png)
![image](https://user-images.githubusercontent.com/16145443/61940891-ed3c9000-afc8-11e9-909c-eb14d8c13fb1.png)

**Comment by adelf** [comment]
Hi, @Chasers9527 .
JetBrains removed 0.7 version from their repository because of problems with integration with GoLand. For PhpStorm you can download .jar file here - https://github.com/adelf/idea-php-dotenv-plugin/releases/tag/v0.7 and then add it to PhpStorm with Settings>Plugins>Install plugin from disk...

**Comment by Chasers9527** [comment]
@adelf OK thanks
