### ISSUE TITLE
Very long analysis of my TS code, with the plugin enabled.

### ISSUE THREAD

**Issue by ethernalsteve** [adelf/idea-php-dotenv-plugin#74]
Hello. The problem was that when running the plugin, my .ts files took a very long time to parse. I've been trying to figure out the reason all day. After disabling your plugin, everything is the same as before. Can you explain this somehow?

**Comment by adelf** [comment]
That's weird. The only place where I touch the JavaScript part of the IDE is turning off Vue support for blade files. There was an issue with infinite indexing, but it's fixed in the last versions - https://youtrack.jetbrains.com/issue/WEB-49838 .

Do you have any `<html>` tags inside your .ts files? Like React component syntax...

**Comment by adelf** [comment]
Sorry. I've messed up my plugins :) 

.env files support plugin only implements `completion contributor` and `gotoDeclarationHandler` features for JavaScript files. They should not make the analysis longer...

Could you check it again? Maybe after File - Invalidate caches & Restart?

**Comment by ethernalsteve** [comment]
After I did File - Invalidate cache & Restart - the problem went away :) Thanks.

**Comment by ethernalsteve** [comment]
> Do you have any `<html>` tags inside your .ts files? Like React component syntax...

No, I do not use html in my code
